name:                coc-api-hs
version:             0.1.0.0
github:              "bendo/coc-api-hs"
license:             BSD3
author:              "Zdeno Osina"
maintainer:          "zdeno.osina@gmail.com"
copyright:           "2019 Zdeno Osina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bendo/coc-api-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- aeson
- lens
- lens-aeson
- wreq
- regex-tdfa
- regex-base
- bytestring
- text
- time
- yaml

library:
  source-dirs: src

executables:
  coc-api-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coc-api-hs

tests:
  coc-api-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coc-api-hs
